apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-echo-server
  template:
    metadata:
      labels:
        app: wasm-echo-server
    spec:
      runtimeClassName: wasm
      containers:
        - name: wasm-echo-server
          image: frederikpietzko/wasm-echo-server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-echo-server
spec:
  selector:
    app: wasm-echo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
